### ISSUE TITLE
Import opml file ，NOT paste file content.

### ISSUE THREAD

**Issue by ZetaoYang** [z-------------/cumulonimbus#10]
Thank you for this beautiful and useful desktop client. 
I think importing other podcast source via opml file would be better, instead of pasting their content to that input box.
Thank you again. Good work!

**Comment by z-------------** [comment]
Thanks for the kind words and I'm glad you like Cumulonimbus. I'll work on adding your suggestion soon.

**Comment by z-------------** [comment]
@ZetaoYang, I've made the OPML import use a file instead of pasted text as input, per your suggestion, in commit 4c978efd6d1b361c346a7d720f3e88a1aac3372b. I'll release it as version 1.7.0 along with a offline playback feature when I've finished testing.

**Comment by ZetaoYang** [comment]
@z-------------  Thank you,I will have a try.

**Comment by ZetaoYang** [comment]
Could add single podcast url manually by "ADD" button?

**Comment by z-------------** [comment]
@ZetaoYang Sure thing. I'll add it soon.

**Comment by z-------------** [comment]
@ZetaoYang In commit 71b23a3f782f6578118b80075be1c6cd2fd5aa0d, I've added the ability to paste a feed URL into the Search bar in the Explore tab to go directly to that podcast.
