### ISSUE TITLE
Keeping track of play progress

### ISSUE THREAD

**Issue by lamarios** [z-------------/cumulonimbus#12]
It would be good to have a feature to keep track of the progress of podcast play so that i could stop the application and start it later and continue from where i left off.

Great app ! Keep it up.

**Comment by z-------------** [comment]
That's weird – I have built in that functionality. I must have broken something between now and then. I'll fix it soon.

Thank for the kind words and for pointing this out.

**Comment by z-------------** [comment]
I've just tried it myself, and it does seem to remember where I left off. Would you mind giving me information about what specific podcasts have you tried this with so I can further try to reproduce the problem?

**Comment by lamarios** [comment]
Sorry you are right, when quitting the app, it does keep track whens tarting it again but when switching between podcasts it doesn't.

**Comment by z-------------** [comment]
That's a good point. I'll add this functionality to my to-do list.

**Comment by z-------------** [comment]
Hello @lamarios, I've added the functionality you speak of in [(pre)release 1.9.0](https://github.com/z-------------/cumulonimbus/releases/tag/v1.9.0).

You can install the new version manually from that link, or wait a little while for release 1.9.1 which will address #14 and which will be available via the auto-updater.

**Comment by lamarios** [comment]
Great, thanks !
