### ISSUE TITLE
keep track of unlistened episodes

### ISSUE THREAD

**Issue by de-vries** [z-------------/cumulonimbus#14]
Hi Zack, I've been trying Cumulonibus and claiming that it's simple and beautiful is nothing near an exaggeration. However, there is one missing feature that's kind of a deal-breaker for me. I wish the app would track what episodes I listened to, so I can have a quick overview of unlistened episodes.

The way I would design this is to put a icon everywhere the 'add to queue' and 'play' buttons are. This icon should change when you play an episode, but also be clickable itself so you can trigger the played/unplayed status of an episode.
As an extra, It would be nice to be able to filter on the played/unplayed status.

**Comment by probonopd** [comment]
Will also be needed for https://github.com/z-------------/cumulonimbus/issues/11

**Comment by z-------------** [comment]
@de-vries, thanks for the suggestion and encouragement. I will implement the functionality you speak of along with #12. As for 11, @probonopd, I imagine that will come later as it's a bigger task and I will have to wait until I have time to focus more on development.

**Comment by z-------------** [comment]
@de-vries Commit b156d0d adds the functionality you speak of and will be available as [(pre)release 1.9.7](https://github.com/z-------------/cumulonimbus/releases/tag/v1.9.7) as soon as it's done building. Please let me know if there are any problems.
