### ISSUE TITLE
Cannot play and pause using the space bar

### ISSUE THREAD

**Issue by probonopd** [z-------------/cumulonimbus#19]
Cannot play and pause using the space bar if the focus is not already on the play button.

It works when it is like this:

![works](https://user-images.githubusercontent.com/2480569/34437162-485a6e90-ec9c-11e7-82db-be617d2640e0.png)

However it does __not__ work when it is like this:

![doesnotwork](https://user-images.githubusercontent.com/2480569/34437164-4963ff68-ec9c-11e7-8022-33375c19e52f.png)

Unfortunately, it is like in the second picture most of the time.

**Comment by z-------------** [comment]
Currently the J, K, and L keys can be used to rewind, play/pause, and skip ahead, respectively. I'll add spacebar as an alternative for play/pause.

**Comment by z-------------** [comment]
[Release 1.9.2](https://github.com/z-------------/cumulonimbus/releases/tag/v1.9.2) addresses this issue.
