### ISSUE TITLE
Handle smaller window sizes more gracefully

### ISSUE THREAD

**Issue by probonopd** [z-------------/cumulonimbus#20]
Please handle smaller window sizes more gracefully (adaptive/responsive design), right now it seems usable basically only in full-screen mode.

![adaptive](https://user-images.githubusercontent.com/2480569/34437200-947797a8-ec9c-11e7-89ff-d22c80f1ebd5.png)

**Comment by z-------------** [comment]
I'll probably make the player section collapse into an expandable bar at the bottom of the window at smaller sizes. Thanks for bringing this up.

**Comment by z-------------** [comment]
Progress is being made on this issue; commit dc7d1c280c6c6051a0aa0bbbab73488d8e51f8e7 improves layout for smaller (but not very small) windows.

**Comment by z-------------** [comment]
[(Pre)release 1.17.0](https://github.com/z-------------/cumulonimbus/releases/tag/v1.17.0) includes 3 layouts for different sizes of window.
