### ISSUE TITLE
Search within a podcast for an episode

### ISSUE THREAD

**Issue by probonopd** [z-------------/cumulonimbus#21]
It would be cool if it would be possible to search within a podcast for a certain episode.

**Comment by z-------------** [comment]
Indeed. I will add this functionality.

**Comment by z-------------** [comment]
@probonopd, I've added this functionality in commit f63a18e and it is part of [(pre)release 1.9.9](https://github.com/z-------------/cumulonimbus/releases/tag/v1.9.9) which will be available as soon as it's done building.
