### ISSUE TITLE
Include AudioVideo Category for Linux desktop file

### ISSUE THREAD

**Issue by nedrichards** [z-------------/cumulonimbus#22]
According to the desktop menu specification you [also need to include AudioVideo](https://specifications.freedesktop.org/menu-spec/latest/apa.html) if you include [Audio as a category](https://github.com/z-------------/cumulonimbus/blob/master/package.json#L83). This could prevent the app showing up correctly in Linux app stores.

([replaces this issue on flathub](https://github.com/flathub/com.github.z.Cumulonimbus/issues/1)).

**Comment by z-------------** [comment]
I don't know much about .desktop files, but [(pre)release 1.9.3](https://github.com/z-------------/cumulonimbus/releases/tag/v1.9.3) makes it so that the `Categories` field is `Audio;AudioVideo;`. Hopefully this solves the issue.

**Comment by nedrichards** [comment]
Thanks! That should fix it.
