### ISSUE TITLE
Change font color for dark background in podcast description

### ISSUE THREAD

**Issue by csgroen** [z-------------/cumulonimbus#23]
When the podcast description tab background is dark, cumulonimbus doesn't automatically detect and change font color to white (or light).

![screenshot from 2018-01-08 11-39-47](https://user-images.githubusercontent.com/17986920/34673349-126f2526-f469-11e7-85d0-79fc30ddd754.png)

Should be a simple fix.

**Comment by z-------------** [comment]
Cumulonimbus used to do this but I broke something along the way. [(Pre)release 1.9.4](https://github.com/z-------------/cumulonimbus/releases/tag/v1.9.4) solves the issue.

Please let me know if there are any problems. I will close this issue for now.
