### ISSUE TITLE
Support video podcast playback

### ISSUE THREAD

**Issue by justinnichols** [z-------------/cumulonimbus#25]
I've subscribed to a few video podcasts, but when playing only the audio is played.  It would be great to have Cumulonimbus support video playback as well.  Thanks!

**Comment by z-------------** [comment]
This is something I'll work on adding. Thanks for the suggestion.

**Comment by justinnichols** [comment]
Thank you!  If I get the opportunity, I will also attempt to contribute to this feature.

**Comment by z-------------** [comment]
I've added support for video podcasts in commit 3e2da1bfbe2817105795ed23faf9a1cf4c4733a2 and this is part of [(pre)release 1.12.0](https://github.com/z-------------/cumulonimbus/releases/tag/v1.12.0). Please let me know if there are any problems.
