### ISSUE TITLE
support for appimaged

### ISSUE THREAD

**Issue by Lvaskz** [z-------------/cumulonimbus#26]
hi, i am using linuxmint 18.03, 64 bits, cinnamon. Actually i installed the appimage daemon called appimaged.
This is appimaged "appimaged is an optional daemon that watches locations like ~/bin and ~/Downloads for AppImages and if it detects some, registers them with the system, so that they show up in the menu, have their icons show up, MIME types associated, etc. It also unregisters AppImages again from the system if they are deleted. If firejail is installed, it runs the AppImages with it."https://github.com/AppImage/AppImageKit
Many appimages, using this can register the icon in the system menu without installing, only putting the appimages on the bin folder or download folder, etc but many icons appimages are not recognized by appimaged, like rambox, vlc, nextcloud, protonmail etc.
By that reason i request if this is posible, cumulonimbus can be supported by appimaged
![cumu](https://user-images.githubusercontent.com/29207169/35487932-1a0254fa-0447-11e8-84cb-621c12ba0d10.png)

**Comment by Lvaskz** [comment]
the icon is not appear in the application menu, not taskbar
![cumu1](https://user-images.githubusercontent.com/29207169/35487948-4f860f54-0447-11e8-99cf-987b7adddd87.png)

**Comment by z-------------** [comment]
Hello Lvaskz, this is a known issue and has already been brought up in #18. The reason is that Cumulonimbus currently does not have an icon at all. I will add one in the future. Thanks.
