### ISSUE TITLE
Remember previous window size

### ISSUE THREAD

**Issue by benjamindaines** [z-------------/cumulonimbus#29]
OS: GNU/Linux
Enviornment: Gnome 3

Currently the program defaults to a full screen window.  It would integrate better if cumulonimbus remembered the previous window size.

**Comment by z-------------** [comment]
Will do. Thanks.

**Comment by z-------------** [comment]
I've added this functionality in commit bd26832 and it's available in [release 1.11.0](https://github.com/z-------------/cumulonimbus/releases/tag/v1.11.0). Please let me know if there are any problems. Thanks!
