### ISSUE TITLE
Playback speed option

### ISSUE THREAD

**Issue by albaphysic** [z-------------/cumulonimbus#30]
Loving the app, very nice work :)

Would be cool to have a playback speed adjustment to speed up podcasts, preferably fine control at 0.1x intervals, similar to Pocket Casts for android: https://i.imgur.com/54sG9aO.jpg

Maybe something more mouse friendly than a slider? Unless it could have scroll wheel support

**Comment by z-------------** [comment]
Hi @albaphysic, I'm glad you like CPod/Cumulonimbus.
Thanks for the suggestion. I'll likely implement it under a new Toggles button to the right of the player slider as an `<input type="number">`.

**Comment by albaphysic** [comment]
Awesome :)

PS. Not related, but you asked for feedback regarding the new name and I think cpod is perfect. Much easier to remember

**Comment by z-------------** [comment]
I've added this functionality in commit 377a491 and it is available in [(pre)release 1.16.0](https://github.com/z-------------/cumulonimbus/releases/tag/v1.16.0). Please let me know if there are any problems.

**Comment by albaphysic** [comment]
Works great :)
