### ISSUE TITLE
Large line spacing in episode descriptions

### ISSUE THREAD

**Issue by Noahkiq** [z-------------/cumulonimbus#31]
The spacing after newlines in the episode descriptions seems to have grown a lot in one of the previous updates. This could be intentional, but if so, an option to remove it might be nice as it looks a little weird with some podcasts.

Cumulonimbus 1.9.6: 
![image](https://user-images.githubusercontent.com/13265322/36238653-fa516c52-11d1-11e8-8b21-7a12a6a5dbb9.png)

CPod 1.14.0: 
![image](https://user-images.githubusercontent.com/13265322/36238687-2e6f2ef2-11d2-11e8-809b-7911c656242f.png)

**Comment by z-------------** [comment]
Hi @Noahkiq, this is the result of me trying to insert `<br>` tags for descriptions that only use newlines. The side effect of this is as you describe: descriptions that use `<br>` tags as well as newlines end up with very large breaks. I will try to find a better way to handle both cases.

**Comment by Noahkiq** [comment]
I see! Thanks for the fast response :)

**Comment by z-------------** [comment]
On an unrelated note, could you tell me what operating system you are on? I've tried to set up the CSS font stacks to use the system font(s), but it seems yours has fallen back to Roboto.

**Comment by z-------------** [comment]
I've addressed this issue in commit 410ea0ed0dcbbb8ebd0e13df5f2d8ed5bced8e37 and it's part of [(pre)release 1.15.0](https://github.com/z-------------/cumulonimbus/releases/tag/v1.15.0). That release seems to introduce some major bugs though, so you might want to wait until that's resolved before trying it out. Thanks!

**Comment by Noahkiq** [comment]
I'm running Fedora 27 with XFCE.

**Comment by Noahkiq** [comment]
oh, I guess I should've mentioned the font hasn't fallen back to anything:

![image](https://user-images.githubusercontent.com/13265322/36277738-bd6542a8-125f-11e8-85c4-6f9fbe316d99.png)

:P
