### ISSUE TITLE
Add support for appimaged 

### ISSUE THREAD

**Issue by Lvaskz** [z-------------/cumulonimbus#33]
Hi, I know cpod has New icon that is great, but AppImaged do not recognize the icon in the App menu, not icon in the taskbar

**Comment by z-------------** [comment]
Thanks for letting me know. I'll be sure to look into it. Just to confirm: you are using version 1.13.1 or above, right?

**Comment by Lvaskz** [comment]
1.50

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by Lvaskz** [comment]
Hi, i have 1.15 version Cpod  in linuxmint 18.3, 64 bits, cinnamon desktop

Sent with [ProtonMail](https://protonmail.com) Secure Email.

-------- Original Message --------

**Comment by z-------------** [comment]
Got it. I'll find out what the problem is.

**Comment by z-------------** [comment]
Hello, [(pre)release 1.19.5](https://github.com/z-------------/cumulonimbus/releases/tag/v1.19.5) contains a fix for this issue. I have tested installing it myself on Ubuntu and the icon seems to show properly (see images below).

Please let me know if the problem is solved on your end.

![Screenshot 1](https://i.imgur.com/3Qv8WFR.png)
![Screenshot 2](https://i.imgur.com/wTKyZgO.png)
![Screenshot 3](https://i.imgur.com/mGx7svB.png)

**Comment by z-------------** [comment]
I'll be closing this for now. Let me know if there are any problems and I'll reopen the issue. Thanks.

**Comment by Lvaskz** [comment]
Well, the problem persist but I need more time to show you an image

**Comment by Lvaskz** [comment]
I think, you can ask some help to @probono. The App is registred in the App menu, but without icon. In the task bar the icon appears, but I repeat not in the App menu.  It is important yo say that I am using AppImage daemon, so the installation script is not using. If I uninstall AppImaged  the script working well, registering the icon in the App menu and the task bar, but it suppost that AppImaged born to not use that script.  Asking provino, Maybe he can help.

**Comment by z-------------** [comment]
Having read the discussion in the similar issue you opened in protonmail-desktop/application, I think part of the problem may be that the version of electron-builder currently used produces type-1 AppImages. I will try updating the electron-builder to produce type-2 AppImages and we'll see if that helps.

**Comment by Lvaskz** [comment]
Ok thanks

**Comment by z-------------** [comment]
I've updated electron-builder and allowed appimaged to automatically install a newly-built version of CPod, and for me the icon shows properly in the app list as well as the taskbar. Please try [(pre)release 1.19.8](https://github.com/z-------------/cumulonimbus/releases/tag/v1.19.8) and let me know if it works for you.

**Comment by Lvaskz** [comment]
Perfect
