### ISSUE TITLE
I can't seem to import my OMPL file containing my podcasts.

### ISSUE THREAD

**Issue by GlacierFox** [z-------------/cumulonimbus#35]
I'm on Ubuntu 17.10. I have a OMPL file containing around 30 podcasts. After importing I get a message that it may take some time to import them all. I've left Cpod working for a few hours a few times and never managed to import my podcasts. I can successfully import them into Pocketcasts and Grover.

I'm using the downloaded .deb version on my system and it has a connection to the internet.

I'll include a copy of my ompl file too in case you want to try and diagnose it for other users importing a large number of podcasts. I'll change the file to .txt so it will upload here.

[Podcasts.txt](https://github.com/z-------------/cumulonimbus/files/1757000/Podcasts.txt)

**Comment by z-------------** [comment]
Thanks, I'll look into it.

**Comment by cobsen** [comment]
I had a similar issue where the dialogue never disappeared. But when I closed it manually Cpod started to display import notifications and every podcast from my OMPL was in my list

**Comment by z-------------** [comment]
@GlacierFox, I've just tried importing subscriptions from the opml file you attached and it seems to work fine. So it's likely that what @cobsen describes is the issue we're facing here, since Electron's dialogs are process-blocking. Could you try importing the opml file again and closing the dialog when it shows? In any case, I'll replace the dialog with something else.

**Comment by GlacierFox** [comment]
Hi there. I just tried what you described and yes it does work if I do that. I think changing the text in the box would be a good idea. Fantastic work by the way, love the app so far.

**Comment by z-------------** [comment]
I've replaced the dialog box with a snackbar (the little dark grey notifications in the bottom left) so it no longer blocks the import. This change is available in [(pre)release 1.17.1](https://github.com/z-------------/cumulonimbus/releases/tag/v1.17.1). Thanks!
