### ISSUE TITLE
Tiny show notes?

### ISSUE THREAD

**Issue by Noahkiq** [z-------------/cumulonimbus#36]
Noticed this little box in the queue which seems to be show notes, but it's incredibly small and seemingly has some lines replaced with nothing
![image](https://user-images.githubusercontent.com/13265322/36765117-b36b205e-1bfd-11e8-883a-2bc95584560d.png)
[cpod 1.17.0]

**Comment by z-------------** [comment]
It's probably a problem with the CSS. I'll look into it.

**Comment by z-------------** [comment]
[(Pre)release 1.17.1](https://github.com/z-------------/cumulonimbus/releases/tag/v1.17.1) includes a fix for this. Thanks!
