### ISSUE TITLE
Add Spanish translate

### ISSUE THREAD

**Issue by Lvaskz** [z-------------/cumulonimbus#37]
hi, this is a good app, and i would like see it translated to spanish and other languages.
You  can translate it using google translate or i can help translating( to spanish), only show me how.( I am not programmer by the way)

**Comment by z-------------** [comment]
Hi Lvaskz, translation sounds like a good idea. I'll first set up the internationalization system for English and then I'll get back to you about how you can help translating to Spanish.

**Comment by Lvaskz** [comment]
Ok

**Comment by z-------------** [comment]
Hi Lvaskz, I've set up the internationalization system and have attempted to add some Spanish translations here: https://github.com/z-------------/cumulonimbus/blob/lang-es/locales/es.json. If you want to help out, you can click the Edit button there, make some improvements, then submit a pull request. Thanks!

**Comment by z-------------** [comment]
Hi Lvaskz, I've put together an attempt at a Spanish translation which you can view [here](https://github.com/z-------------/cumulonimbus/blob/master/locales/es.json). Please feel free to submit a pull request to improve it.

**Comment by z-------------** [comment]
I have release [(pre)release 1.17.2](https://github.com/z-------------/cumulonimbus/releases/tag/v1.17.2) which includes, among other improvements, the Spanish translation. Please try it and let me know if there are any problems. Thanks!

**Comment by Lvaskz** [comment]
Ok thanks

**Comment by Lvaskz** [comment]
Hi, I tried it, it is great thanks
