### ISSUE TITLE
OPML import fails 

### ISSUE THREAD

**Issue by funkypitt** [z-------------/cumulonimbus#38]
Hello,

OPML import fails ("subscriptions now importing" pop-up appears, and then it's stuck) with the attached opml file on Fedora gnome with version 1.9.6 from flathub.

[podcasts.opml.zip](https://github.com/z-------------/cumulonimbus/files/1777369/podcasts.opml.zip)

**Comment by z-------------** [comment]
Hi, I'll look into it. Thanks.

**Comment by funkypitt** [comment]
My apologies, I just realized that the flathub version was not the latest, and that the app had a new name. With the current version installed as an Appimage, it works flawlessly.
