### ISSUE TITLE
Strings to localize

### ISSUE THREAD

**Issue by smarquespt** [z-------------/cumulonimbus#42]
Please check screenshot. Those strings could/should be adde to source files?
![screenshot](https://user-images.githubusercontent.com/1302668/37084834-7581d956-21eb-11e8-99da-aac0c9c673bf.png)

**Comment by z-------------** [comment]
Will do. Thanks.

**Comment by z-------------** [comment]
Commit bfa19c823fa83808d76e343cfcba583f6024c0da makes those strings localizable.
