### ISSUE TITLE
Ability to reorder que 

### ISSUE THREAD

**Issue by benjamindaines** [z-------------/cumulonimbus#48]
It would be a nice addition to add the ability to drag / drop episodes to new locations in the que.

**Comment by z-------------** [comment]
Hi benjamindaines, [(pre)release 1.22.0](https://github.com/z-------------/cumulonimbus/releases/tag/v1.22.0) adds this functionality. Please let me know if there are any problems.

**Comment by tvaz** [comment]
This works fantastic! Thanks so much for adding!
