### ISSUE TITLE
Pressing the spacebar in certain circumstances toggles between play/pause twice, resulting in no change

### ISSUE THREAD

**Issue by Noahkiq** [z-------------/cumulonimbus#51]
Basically, if you click on the pause/play button, an orange box will appear around it.
![image](https://user-images.githubusercontent.com/13265322/38107972-6b4fce16-3361-11e8-8332-487de2961b5a.png)
Now, while this orange box is still there (which stays until you click elsewhere), if you press the spacebar, it will attempt to do the built-in play/pause feature while also acting as a click on the button, resulting in the play/pause status not changing.

Tested on Arch Linux (specifically, antergos) / CPod v1.22.0

**Comment by z-------------** [comment]
I should have foreseen that. Thanks for letting me know. I'll put out a fix soon.

**Comment by z-------------** [comment]
[(Pre)release 1.22.2](https://github.com/z-------------/cumulonimbus/releases/tag/v1.22.2) includes a fix for this. When player control buttons have focus, keyboard shortcuts will take priority and hitting spacebar will not register as a click.
