### ISSUE TITLE
Some feeds are not parsed properly (and don't play)

### ISSUE THREAD

**Issue by 3v1n0** [z-------------/cumulonimbus#56]
I'm trying to play some feeds but while the content is fine, CPod doesn't start playing or show infos other than the title.

For example:
  - https://www.rsi.ch/rete-tre/programmi/intrattenimento/il-disinformatico/?f=podcast-xml (same for the [itunes URI](pcast://www.rsi.ch/rete-tre/programmi/intrattenimento/il-disinformatico/?f=podcast-xml&type=itunes).
 - http://www.radioglobo.it/podcast/morning_show.xml

And others...

**Comment by z-------------** [comment]
Thanks for letting me know. I will look into it.

**Comment by z-------------** [comment]
[(Pre)release 1.23.1](https://github.com/z-------------/cumulonimbus/releases/tag/v1.23.1) solves the problem for the two podcasts you linked (it was related to CPod expecting the episode description to exist and failing when it didn't). Please let me know if there are any further problems.
