### ISSUE TITLE
Markup in episode descriptions

### ISSUE THREAD

**Issue by tvaz** [z-------------/cumulonimbus#62]
I'm not really sure if this is a bug, but I've noticed that episode descriptions that include HTML markup get rendered as plaintext. It would be nice if the markup was retained, or at least sanitized somehow so we don't see a bunch of HTML tags in descriptions.

![selection_008](https://user-images.githubusercontent.com/1314648/39839849-65445568-5392-11e8-97c2-8c60416bdf67.png)

**Comment by tvaz** [comment]
This must have been broken in the most recent update somehow, not sure why. It seems to me like CPod was already stripping HTML tags out of episode descriptions. I haven't been able to test it myself due to problems getting development CPod to work, but the CPod I installed from the most recent Debian package is still showing the tags. Hope that helps.

![selection_009](https://user-images.githubusercontent.com/1314648/39840638-f4422a2c-5394-11e8-893a-fb3ded2a3301.png)
![selection_010](https://user-images.githubusercontent.com/1314648/39840639-f45b1e60-5394-11e8-9e1d-53589878873a.png)

**Comment by z-------------** [comment]
Hi, [prerelease 1.23.4](https://github.com/z-------------/cumulonimbus/releases/tag/v1.23.4) addresses this issue. Please let me know if there are any problems.
