### ISSUE TITLE
Cpod 1.21 can't find a url site inf audio

### ISSUE THREAD

**Issue by Lvaskz** [z-------------/cumulonimbus#65]
**CPod version: 1.21**

**Description of the problem:**
I am trying to find this site http://feeds.gracia.org/gavpodcast. The site appears in Cpod but the not the audios. I can not suscribe, I can not do nothing. With others I do well, as: "aviva nuestros corazones"

**Comment by z-------------** [comment]
Hi Lvaskz, the problem seems to be that http://feeds.gracia.org/gavpodcast is not an RSS feed. It works fine if you use http://feeds.gracia.org/gavpodcast&x=1 (found in the page you linked). 

Let me know if that doesn't solve the problem. Thanks.

**Comment by Lvaskz** [comment]
yes, it works, thanks
