### ISSUE TITLE
Media keys cannot be reconfigured

### ISSUE THREAD

**Issue by Noammac** [z-------------/cumulonimbus#66]
**CPod version:** 1.24.1

**Is your feature request related to a problem? Please describe.**
The media keys (e.g. `j`, `k`, `l`) cannot be reconfigured. Their actions cannot be modified in any way, ranging from the duration they skip to the action they perform on the currently playing media upon pressing the designated keys on the keyboard.

**Describe the solution you'd like**
A place in the settings where one may configure what each key does or better yet, a place in the settings where one may configure each of the keys on their keyboard to do whatever they may desire as possible in the scope of CPod.

**Comment by Noammac** [comment]
I had tried to configure the media keys using current configuration
methods, but it had only made matters more confusing.
Your proposed solution seems like it could solve my issue, thank you for
your time.

**Comment by z-------------** [comment]
[Pre-release 1.25.0](https://github.com/z-------------/cumulonimbus/releases/tag/v1.25.0) includes the changes outlined earlier. Please let me know if they solve the issue. Thanks.

**Comment by Noammac** [comment]
Yes, it does solve my issue. Thank you very much.
