### ISSUE TITLE
Scrolling stops if mouse pointer rolls over title label on subscriptions tab 

### ISSUE THREAD

**Issue by benjamindaines** [z-------------/cumulonimbus#67]
**CPod version:** 1.25.2

**Description of the problem:**
When scrolling on the subscriptions tab, if the mouse pointer rolls over a show label, scrolling stops.  Seems like new behavior.

**Comment by z-------------** [comment]
Hi benjamindaines, [v1.25.3](https://github.com/z-------------/cumulonimbus/releases/tag/v1.25.3) includes a fix for this bug. Please let me know if there are any problems.

**Comment by z-------------** [comment]
I'll be closing this for now. I'll reopen if there are any problems. Thanks.
