### ISSUE TITLE
Playback speed control cut off in single column view 

### ISSUE THREAD

**Issue by benjamindaines** [z-------------/cumulonimbus#70]
**CPod version:** 1.25.3

**Description of the problem:**
When cpod is in it's "skinny view" on the expanded playback screen, speed adjustment up / down buttons are pushed beyond the side of the window.  Stays this way no matter the width of the window until "dual column" view is activated. 
![screenshot_20180618_192116](https://user-images.githubusercontent.com/3039460/41567259-49f339e0-732d-11e8-8c43-d4cd4d7af65b.png)

**Comment by z-------------** [comment]
Hi benjamindaines, [v1.25.4](https://github.com/z-------------/cumulonimbus/releases/tag/v1.25.4) contains a fix for this issue. Please let me know if there are any problems.
