### ISSUE TITLE
Downloading of single and multiple episodes for offline consumption

### ISSUE THREAD

**Issue by probonopd** [z-------------/cumulonimbus#8]
Thank you for this extremely useful app. Desktop Linux was seriously missing this!

Please allow for easy downloading of single and multiple episodes for offline consumption.

**Comment by z-------------** [comment]
Hi probonopd, I'm glad you're enjoying Cumulonimbus! I'll work on adding this functionality soon.

**Comment by z-------------** [comment]
I've implemented this in [release 1.7.0](https://github.com/z-------------/cumulonimbus/releases/tag/v1.7.0). Please let me know how you think it can be improved :)

**Comment by probonopd** [comment]
I only see a play button and another button that I do not know what it does. But no download button. How do I download an episode?

![screenshot from 2017-12-27 11-01-05](https://user-images.githubusercontent.com/2480569/34378278-f44d120e-eaec-11e7-9f65-2a8caf82c69c.png)

**Comment by z-------------** [comment]
@probonopd I've only added download buttons to episodes in the Home stream:
![Screenshot](https://i.imgur.com/lYzD89v.png)
I'll add them to the per-podcast view as well. Thanks for pointing this out.

**Comment by probonopd** [comment]
Thanks @z-------------, to be honest the "Explore" tab is all I ever use. I think it should be the first tab and should be selected by default when first opening the app, since without it all other tabs are essentially empty.

**Comment by z-------------** [comment]
@probonopd I probably won't make it default, but I'll work on adding an option to customize the default tab.

**Comment by probonopd** [comment]
Maybe jump to that tab as long as no podcasts are subscribed? I don't think that may users will bother to go to the settings.

**Comment by z-------------** [comment]
Seems like a good idea.

**Comment by z-------------** [comment]
These issues should be addressed in commits c8172ec8ab6344f392f2e152349e54633d003f26 
 and 5e9725d25f101fdc452f6d3893799e32e5c7d5da, respectively. Please let me know if there are any problems.

**Comment by z-------------** [comment]
[Here](https://github.com/z-------------/cumulonimbus/releases/tag/v1.7.2) is the new release.

**Comment by probonopd** [comment]
Thank you very much, very useful.
